### PR TITLE
Add 3dj models for use with sc-goodies and update readme.md

### PR DESCRIPTION
**Pull request by dimaguy**
I've successfully managed to frankenstein and coerce lemmmy's web converter into working with bulk files within a node.js local instance, which allowed me to painlessly convert all of the old 3dm models to 3dj.

Maybe these could serve as examples on usage

### CODE REVIEW

**Comment by emmachase** [comment]
Cool diff

**Comment by Lemmmy** [comment]
I’m glad that you frankensteined my web converter so that you could painlessly convert my readme into a slightly longer readme

**Comment by dimaguy** [comment]
This is what happens when I attempt to code late at night, mistakes

**Comment by Lemmmy** [comment]
Thanks!

**Pull request merged**
